### PR TITLE
Update short user documentation

### PR DESCRIPTION
**Pull request by mpejcoch**

### CODE REVIEW

**Comment by johtoblan** [comment]
```
~/Desktop/S-ENDA/mms/go-mms$ make
go mod download
statik -f -src=static -dest=pkg
make: statik: Command not found
Makefile:23: recipe for target 'statik' failed
make: *** [statik] Error 127

```

**Comment by johtoblan** [comment]
this is what I get after doing make deps first of course.

**Comment by johtoblan** [comment]
Fixed by sudo apt install golang-statik . Should make clear dependancy or?

**Comment by mpejcoch** [comment]
Make deps installs it, but perhaps you don't have $GOBIN in your path, should be either described or checked for by the makefile.

**Review by johtoblan — APPROVED** [review]

**Comment by johtoblan** [comment]
Fixed by using correct path.

**Review by johtoblan — APPROVED** [review]

**Review by vkbo — APPROVED** [review]

**Pull request merged**
